import { InvitedGuest } from '../../../app/booking/model/entities/invited-guest.entity';

const nowPlusFive = new Date();
nowPlusFive.setDate(nowPlusFive.getDate() + 5);

export const invitedGuestsSample: InvitedGuest[] = [
  {
    id: 1,
    modificationCounter: 1,
    bookingId: 4,
    guestToken: '***REMOVED***',
    email: 'guest0@mail.com',
    accepted: true,
    modificationDate: nowPlusFive,
    orderId: 2,
  },
  {
    id: 2,
    modificationCounter: 1,
    bookingId: 4,
    guestToken: '***REMOVED***',
    email: 'guest1@mail.com',
    accepted: true,
    modificationDate: nowPlusFive,
    orderId: 3,
  },
  {
    id: 3,
    modificationCounter: 1,
    bookingId: 4,
    guestToken: '***REMOVED***',
    email: 'guest2@mail.com',
    accepted: false,
    modificationDate: nowPlusFive,
    orderId: 4,
  },
  {
    id: 4,
    modificationCounter: 1,
    bookingId: 4,
    guestToken: '***REMOVED***',
    email: 'guest3@mail.com',
    accepted: true,
    modificationDate: nowPlusFive,
    orderId: 5,
  },
  {
    id: 5,
    modificationCounter: 1,
    bookingId: 4,
    guestToken: '***REMOVED***',
    email: 'guest4@mail.com',
    accepted: false,
    modificationDate: nowPlusFive,
    orderId: 6,
  },
  {
    id: 6,
    modificationCounter: 1,
    bookingId: 4,
    guestToken: '***REMOVED***',
    email: 'guest5@mail.com',
    accepted: true,
    modificationDate: nowPlusFive,
  },
  {
    id: 7,
    modificationCounter: 1,
    bookingId: 4,
    guestToken: '***REMOVED***',
    email: 'guest6@mail.com',
    accepted: false,
    modificationDate: nowPlusFive,
  },
  {
    id: 8,
    modificationCounter: 1,
    bookingId: 4,
    guestToken: '***REMOVED***',
    email: 'guest7@mail.com',
    accepted: true,
    modificationDate: nowPlusFive,
  },
  {
    id: 9,
    modificationCounter: 1,
    bookingId: 4,
    guestToken: '***REMOVED***',
    email: 'guest0@mail.com',
    accepted: true,
    modificationDate: nowPlusFive,
    orderId: 7,
  },
  {
    id: 10,
    modificationCounter: 1,
    bookingId: 4,
    guestToken: '***REMOVED***',
    email: 'guest1@mail.com',
    accepted: false,
    modificationDate: nowPlusFive,
    orderId: 8,
  },
];
