apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mts-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mmehrazar/my-thai-star-microservices.git
    targetRevision: HEAD
    path: Mts-k8s
  
  destination:
    server: https://kubernetes.default.svc
    namespace: my-thai-star

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
   
    automated:
      selfHeal: true
      prune: true